services:
  mongo1:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db1:/data/db
      - configdb1:/data/configdb
    command:
      ["--replSet", "rs0", "--bind_ip", "localhost,mongo1", "--port", "27017"]

volumes:
  db1:
  configdb1:
